widgets = [
    "Checkbutton",
    "FloatCombobox",
    "FormWidget",
    "Frame",
    "OptionMenu",
    "PageNavigator",
    "LabelFrame",
    "DirectoryEntry",
    "TextEntry",
    "FloatEntry",
    "IntegerEntry",
    "Value",
    "RegionSelector",
    "Scale",
]
